Algoritmo "Desafio Sextou"

Var
       anacleto, ana, felis, felisberto:real
       ano:inteiro

Inicio

      anacleto<-1.50
      felisberto<-1.10

    enquanto (anacleto>felisberto) faca
        ano<-ano+1
        anacleto<-anacleto+0.02
        felisberto<-felisberto+0.03
        
    fimenquanto
    
    escreval("Demorou ",ano," anos. Felsiberto teria ",felisberto," e Anacleto teria ",anacleto)
        


Fimalgoritmo