algoritmo "Programa Potencia - Desafio 7"
  //variável de modo inteiro
  var n1, n2, potencia: real

 inicio
//Aba de recepção
escreval("Olá, Seja Bem Vindo(a)")
escreval("")

//Aba onde digita-se os dois números para a potência
  escreval("Digite um número")
  leia(n1)
escreval("Digite um número")
  leia(n2)

potencia<-n1^n2 //numero 1 elevado ao nunero 2

//Aba onde mostrara a potência do número
escreval ("A pontecia de ",n1, " elevado a  ",n2," é ", potencia)
  fimalgoritmo