Algoritmo "semnome"
// Linguagem e Lógica de Programação 
// Curso em Vídeo 
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/01/2023
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Ola, mundo!")
Escreva ("Me livrei da maldição")

Fimalgoritmo