algoritmo "Programa Negativo - Desafio 3"

  var neg, n: real

inicio
  escreval ("Seja Bem Vindo (a) ao nosso Sistema")


    escreval ("Digite um número ")
    leia(n)
escreval ("Digite um número ")
    leia(n)
escreval ("Digite um número ")
    leia(n)
escreval ("Digite um número ")
    leia(n)
escreval ("Digite um número ")
    leia(n)

    se (n<0) então
       neg<- +1
    fimse
  escreval (" Quantidade de numeros negativos --:",neg)

  fimalgoritmo