algoritmo "Positivo, Negativo ou Nulo - Desafio 2"

//variável número de modo inteiro
  var n: real

 inicio

   escreval ("Olá, Seja Bem vindo (a) ao nosso sistema")
   escreval("")
  escreval("Digite um número:")
leia(n)

se (n>0) entao
escreval ("O número ",n," é POSITIVO")
fimse
se (n<0) entao
escreval ("O número ",n," é NEGATIVO")
fimse
se (n=0) entao
escreval ("Esse número é NULO")
fimse

  fimalgoritm