Algoritmo "Aula 02"
// Linguagem e Lógica de Programação 
// Curso em Vídeo 

Var
//Var / Variáveis são espaços na memória que vão
//guardar valores
   msg: Caractere
Inicio
      msg <- "Olá, mundo!"
//msg está recebendo a mensagem "Olá,Mundo!"
      Escreval("msg")
//Vai escrever o que ta pedindo : msg
      Escreval(msg)
//Vai escrever o conteúdo da variável msg
      Escreva("Senha aceita ", msg)
//Vai escrever Mensagem dar um espaço e escrever o
//conteúdo da variável msg

Fimalgoritmo