Algoritmo "semnome"
// Linguagem e Lógica de Programação
// Curso em Vídeo 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/01/2023
Var
// Seção de Declarações das variáveis 
   x: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
      x <- 0
      Enquanto ( x <= 10 ) faça
               Escreval(x)
               x <- x + 1
      FimEnquanto
Fimalgoritmo