Algoritmo "Dia 12"
// Linguagem e Lógica de Programação
// Curso em Vídeo 
Var
// Seção de Declarações das variáveis 
   Valor, Imposto, Parcela: Real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("Qual valor você deseja saber ? ")
   Leia(Valor)
   Escreval("Qual será o imposto ? " )
   Leia(Imposto)
   Parcela <- Valor * Imposto / 100
   Escreval("O valor de cada parcela será de", Parcela)
Fimalgoritmo