Algoritmo "Dia 44"
// Linguagem e Lógica de Programação
// Curso em Vídeo
// Contando negativamente
Var
// Seção de Declarações das variáveis
   x: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
      Escreva("Até quanto você quer diminuir ? ")
      Leia(x)
      Escreval("Lembrando que iremos até 0")
      Enquanto ( x >= 0 ) faça
               Escreval(x)
               x <- x - 1
      FimEnquanto
Fimalgoritmo